[package]
name = "qlog"
version = "0.8.0"
authors = ["Lucas Pardue <lucaspardue.24.7@gmail.com>"]
edition = "2018"
description = "qlog data model for QUIC and HTTP/3"
repository = "https://github.com/cloudflare/quiche"
readme = "README.md"
keywords = ["qlog", "quic", "http3"]
categories = ["network-programming"]
license = "BSD-2-Clause"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
serde_derive = "1.0"
serde_with = "1.3.1"
